imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         
        cookie_lifetime: 28800
        gc_maxlifetime: 3600
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources: 
          - 'BaseBundle:Form:form_table_layout.html.twig'
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        persistent:  true


  orm:
      auto_generate_proxy_classes: true
      #auto_mapping: true
      default_entity_manager: default
      entity_managers:
        default:
          connection: default
          auto_mapping: true

              
doctrine_mongodb:
  default_database: %mongo_base%
  connections:
    default:
      server: %mongo_server%:%mongo_puerto%
      options:
        connect: ~
        socketTimeoutMS:  180000
        wTimeoutMS:       180000
        #username: %mongo_usuario%
        #password: %mongo_pass%
        
  document_managers:
    default:
      auto_mapping: true
       

services:
            

knp_paginator:
    page_range: 5  # número de páginas que se muestran en el paginador

    default_options:
        # los siguientes tres parámetros permiten "traducir" el paginador
        # puedes utilizar por ejemplo: 'pagina', 'ordenar' y 'direccion'
        page_name:           pagina
        sort_field_name:     sort
        sort_direction_name: direction
        # sólo incluir resultados diferentes (útil cuando haces consultas GROUP BY)
        distinct: false

    template:
        # estas opciones configuran la plantilla utilizada para la paginación
        # y para los controles que premiten reordenar los resultados
        # pagination: KnpPaginatorBundle:Pagination:sliding.html.twig
        pagination: BaseBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
        sortable:   BaseBundle:Pagination:sortable_link.html.twig
knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf
        options:    
          encoding: UTF8
        #  load-error-handling: ignore
          margin-left: 20
    image:
        enabled:    false
        binary:     /usr/bin/wkhtmltoimagedocument_manager
        options:    []

