acme:
    resource: "@AcmeBundle/Controller/"
    type:     annotation
    prefix:   /

doc:
    resource: "@DocBundle/Resources/config/routing.yml"
    prefix:   /

bds_doctrine:
    resource: "@BDSDoctrineBundle/Controller/"
    type:     annotation
    prefix:   /



#####
