security:
    access_denied_url: /sistema/no_autorizado
    encoders:

        Symfony\Component\Security\Core\User\User: plaintext


    providers:
        in_memory:
            memory: ~

    firewalls:
        main:
            pattern: ^/
            logout:       true
            anonymous:    true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
            anonymous: ~ 

    access_control:
      - { path: ^, role: IS_AUTHENTICATED_ANONYMOUSLY }
    role_hierarchy:
      ROLE_SUPER_ADMIN: ROLE_ADMIN
      
     
